IPS package handling.
johnbellone/chef-updater-cookbook pull request #10
Opened 2016-10-06 20:23 UTC by jjustice6

This not only makes the Chef Updater cookbook capable of handling IPS
packages, it correctly handles upgrading from the pre-IPS package format
as well as works around a bug in the "solaris_package" resource which
necessitates using the shell script mechanism for removing the prior
version of the package.

Please do not merge this until we know exactly what the exact package name from Chef is going to look like, since it might be "#{arch}.p5p" without the extra .solaris in there, or there might be other changes.

2016-10-07 10:44 UTC, johnbellone requested changes
It overall looks good, just a few things.

2016-10-07 10:44 UTC, johnbellone commented on libraries/chef_updater.rb
> +            provider Chef::Provider::Package::Ips if platform?('solaris2') && new_resource.use_ips_package
I would just change

2016-10-07 10:44 UTC, johnbellone commented on libraries/chef_updater.rb
> +              code 'yes | pkgrm chef'
It is not `echo 'yes'`?

2016-10-10 18:31 UTC, jjustice6 commented on libraries/chef_updater.rb
> +            provider Chef::Provider::Package::Ips if platform?('solaris2') && new_resource.use_ips_package
wait, what are you wanting to change here? it looks like part of your comment got wiped.

2016-10-10 21:16 UTC, johnbellone commented on libraries/chef_updater.rb
> +            provider Chef::Provider::Package::Ips if platform?('solaris2') && new_resource.use_ips_package
No idea.

2016-10-10 21:17 UTC, merged